# Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [2]:
import numpy as np

In [13]:
a = np.array([1,2,3, 4])

In [14]:
print(type(a))

<class 'numpy.ndarray'>


In [15]:
print(a.shape)

(4,)


In [6]:
print(a[0], a[1], a[2])

1 2 3


ndim provide dimension of array

In [7]:
print(a.ndim)

1


In [8]:
a[0] = 5

In [9]:
print(a)

[5 2 3]


In [10]:
b = np.array([[1,2],[3, 4],[5,6]])

In [11]:
print(b.shape)

(3, 2)


In [12]:
print(b[0,0], b[0,1], b[1,0])

1 2 3


Numpy also provides many functions to create arrays:

In [17]:
a = np.zeros((2,2))

In [18]:
print(a)

[[ 0.  0.]
 [ 0.  0.]]


In [19]:
b = np.ones((2,3))

In [21]:
print(b)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [22]:
c = np.full((2,3),7)

In [24]:
print(c)

[[7 7 7]
 [7 7 7]]


In [26]:
d = np.eye(4)
print(d)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [31]:
e = np.random.random((2,2))
print(e)

[[ 0.62405506  0.04200887]
 [ 0.27973909  0.95078985]]


# Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [32]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
b = a[:2 ,1:3]
print(b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it
 will modify the original array.

In [35]:
print(a[0,1])

2


In [36]:
b[0, 0] = 77

b[0, 0] is the same piece of data as a[0, 1]

In [37]:
print(a[0,1])

77


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [38]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [42]:
row_r1 = a[1, :] # Rank 1 view of the second row of a

In [44]:
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

In [49]:
print(row_r1 , row_r1.shape) 
print(row_r2, row_r2.shape) 

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [46]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

In [50]:
print(col_r1, col_r1.shape)  

[ 2  6 10] (3,)


In [51]:
print(col_r2, col_r2.shape)

[[ 2]
 [ 6]
 [10]] (3, 1)


# Integer array indexing

 When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [64]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a,a.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [66]:
# An example of integer array indexing.
# The returned array will have shape (3,)
print(a[[0, 1, 2], [0, 1, 0]])

[1 4 5]


In [72]:
# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  

[1 5 7]


In [73]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [74]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

In [75]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [76]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

In [78]:
print(a[np.arange(4),b])

[ 1  6  7 11]


In [79]:
a[np.arange(4), b] += 10

In [82]:
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


# Boolean array indexing

Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [83]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [84]:
bool_idx = (a>2)

In [85]:
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [87]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

[3 4 5 6]


In [88]:
# We can do all of the above in a single concise statement:
print(a[a > 2])     

[3 4 5 6]


# Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [89]:
x = np.array([1,2])

In [90]:
print(x.dtype)

int32


In [92]:
x = np.array([1.0,2.0])
print(x.dtype)

float64


In [93]:
x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int64


In [94]:
x = np.array([1, 2], dtype=np.int8)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int8


In [95]:
x = np.array([1, 2], dtype=np.int8)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int8


# Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [102]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

[[ 1.  2.]
 [ 3.  4.]]
[[ 5.  6.]
 [ 7.  8.]]


In [105]:
print(x+y) 
#or we can use
print(np.add(x,y))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


In [106]:
print(x-y)
#or we can use
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [107]:
# Elementwise product; both produce the array
print(x*y)
print(np.multiply(x,y))

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]


In [108]:
# Elementwise division; both produce the array
print(x/y)
print(np.divide(x,y))

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [110]:
print(np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [113]:
v = np.array([9,10])
w = np.array([11, 12])

In [117]:
print(v.dot(w))
print(np.dot(v, w))

219
219


In [115]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [118]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:

In [119]:
x = np.array([[1,2],[3,4]])

In [120]:
print(np.sum(x))  # Compute sum of all elements; prints "10"

10


In [121]:
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"

[4 6]


In [122]:
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

[3 7]


Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [123]:
x = np.array([[1,2], [3,4]])

In [124]:
print(x)

[[1 2]
 [3 4]]


In [125]:
print(x.T)

[[1 3]
 [2 4]]


In [127]:
# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    
print(v.T)  

[1 2 3]
[1 2 3]


# Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [128]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

In [129]:
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [130]:
v = np.array([1, 0, 1])

In [132]:
y = np.empty_like(x) # Create an empty matrix with the same shape as x

In [133]:
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

In [134]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

In [135]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

In [136]:
v = np.array([1, 0, 1])

In [137]:
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other